= node-post-acceptance

== When/What ?

This directory contains hooks executed after a node was successfully accepted. 

Typically, these hooks triggers action on other system, like registering the node
into a monitoring system or into an external CMDB, or to send notification. 

Be careful with non-compliant reports hooks. The may impact the performance of the system if
non-compliant report rate is hight. These hooks should be make to be the most efficient
possible and should execute asynchronuously. 


== Parameters

Hooks parameters are passed by environment variable:

- RUDDER_REPORT_SEVERITY           : report severity level (result_error, result_repaired, audit_noncompliant, audit_error, log_warn)
- RUDDER_REPORT_EXECUTION_DATETIME : date/time (ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ) when log was writen (node local time)
- RUDDER_REPORT_RUN_DATETIME       : date/time (ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ) when run for that log started
- RUDDER_NODE_ID                   : nodeId
- RUDDER_NODE_HOSTNAME             : node fully qualified hostname
- RUDDER_REPORT_RULE_ID            : rule ID of report
- RUDDER_REPORT_RULE_NAME          : rule human readable name of report
- RUDDER_REPORT_DIRECTIVE_ID       : directive ID of report
- RUDDER_REPORT_DIRECTIVE_NAME     : directive human readable name of report
- RUDDER_REPORT_TECHNIQUE_ID       : technique ID from which the directive is derived
- RUDDER_REPORT_TECHNIQUE_VERSION  : technique version from which the directive is derived
- RUDDER_REPORT_COMPONENT_NAME     : component name (i.e key) in the directive for that report
- RUDDER_REPORT_COMPONENT_VALUE    : component value bound to the component name
- RUDDER_REPORT_MESSAGE            : report message
 